### ISSUE TITLE
Unable to access

### ISSUE THREAD

**Issue by yoshida-git-ai** [petitroto/botpress-sheet2bot#7]
{EXTERNAL_URL} / s / sheet2bot in your browser
I can't access it

http: // localhost: 3000 / lite /? m = sheet2bot & v = AppView
The URL will be replaced with

Upload the archive as per the procedure
Switch enabled
Rebooting Botpress

The version is -v12_26_4

Do I need any other settings?

「チャットボットの教科書」を読みましたが解決できていません
![1118](https://user-images.githubusercontent.com/94094919/142354727-7c3c3346-dd23-46bb-a7ef-41bc8ee09987.png)

**Comment by KurahitoYoshida** [comment]
管理画面でモジュールの有効/無効を切り替えた時のログです

```
11/19/2021 10:59:05.418 Launcher Botpress is exposed at: http://localhost:3000 
11/19/2021 10:59:52.471 HTTP A shortlink named "sheet2bot" already exists. 
11/19/2021 10:59:52.474 HTTP Module sheet2bot reloaded successfully! 
```

**Comment by KurahitoYoshida** [comment]
クロームではこのような
![1119](https://user-images.githubusercontent.com/94094919/142558550-440848a1-a51c-4512-aa4a-b1791c0715df.png)

**Comment by KurahitoYoshida** [comment]
リバースプロキシを設定しSSLでexternalUrlを正しく設定したところアクセスできました

**Comment by petitroto** [comment]
@KurahitoYoshida 
解決したということでよろしいでしょうか？

また何かありましたら再オープンしてください。
その際は、再現する環境（OS,Botpress,Sheet2Botのバージョンなど）と手順を詳しく記載いただけると助かります。
